#!/usr/bin/python
#-*-coding:utf-8-*-

import sys
import rospy

from manages.data_conversion import DataConversion

def main():
    print 'switch_connect v 1.0.0'

    try:
        rospy.init_node('BridgeDementia')
        conv = DataConversion()
        # conv.execute()
        rospy.spin()

    except rospy.ROSInterruptException:
        pass

if __name__ == '__main__':
    main()